apiVersion: v1
kind: Service
metadata:
  name: {{ include "automation-dashboard.fullname" . }}-frontend
  labels:
    {{- include "automation-dashboard.labels" . | nindent 4 }}
    component: frontend
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "automation-dashboard.selectorLabels" . | nindent 4 }}
    component: frontend
